### ISSUE TITLE
Run but No Connected on dashboard , why ? 

### ISSUE THREAD

**Issue by T7890u** [cmalf/getgrass-bot-js#2] opened 2024-12-09 16:16 UTC

**Comment by cmalf** [comment] 2024-12-09 16:49
> <img alt="Screenshot 2024-12-09 at 23 45 05" width="1332" src="https://private-user-images.githubusercontent.com/79704582/393921628-25519811-e90e-4400-9f47-1f87bd41121f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NjMxODYsIm5iZiI6MTczMzc2Mjg4NiwicGF0aCI6Ii83OTcwNDU4Mi8zOTM5MjE2MjgtMjU1MTk4MTEtZTkwZS00NDAwLTlmNDctMWY4N2JkNDExMjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDE2NDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZDNiMzMxMTc1OTAzNjdlOTkwZDgyMGFmZGQ1MjA4NDRhMThmMzA0N2FlNDE5OTAwM2IxZDdmZGFkYTA5ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E-ZmlO6KVlG_UppwszzvA6t7s4seVhB9O63miKoKcHA">
> same with me, all the proxy is good but no point and device added. here just my extension run in my dashboard, the point and device from bot not added

which script are you running, the main script(extention version) or the desktop version?

**Comment by heihotech** [comment] 2024-12-09 16:52
can you try with create new account then run the bot?

**Comment by cmalf** [comment] 2024-12-09 17:02
> both of them sir. and i've running it for about 1 hour each but still no new device / ip and point.

okay,I'll investigate the root cause of the issue and provide an update once it's resolved.

**Comment by xingxing-dd** [comment] 2024-12-09 17:21
I also encountered this problem. Has the communication protocol been changed?

**Comment by cmalf** [comment] 2024-12-09 17:32
> I also encountered this problem. Has the communication protocol been changed?

no, the communication protocol has not changed.
![Screenshot 2024-12-10 at 00 29 58](https://github.com/user-attachments/assets/f72bd7fe-e25a-4fc2-bb59-5a76a23243d4)

**Comment by cmalf** [comment] 2024-12-09 21:32
@everyone
Please, Visit Here [discussion](https://github.com/cmalf/getgrass-bot-js/discussions/4)

**Comment by Solana0x** [comment] 2024-12-14 09:03
Is the issue resolved ? i am also working on issue lets work together

**Comment by Solana0x** [comment] 2024-12-14 09:03
as per my guess they added another layer of auth which is coming via some aws hosted platform?

**Comment by cmalf** [comment] 2024-12-14 09:45
> Is the issue resolved ? i am also working on issue lets work together

Yes, I'm working on it, referring to the latest desktop version. (sounds good, but please just continue the discussion section.)

**Comment by Solana0x** [comment] 2024-12-14 11:03
> > Is the issue resolved ? i am also working on issue lets work together
> 
> Yes, I'm working on it, referring to the latest desktop version. (sounds good, but please just continue the discussion section.)

http://wsserv-wsser-2ytaktvectad-200e534a774d479a.elb.us-east-1.amazonaws.com/e65c798e44045cf3241e5bdc52aff12c/YApzWbFjXVEsiT2w

grass is using this api for auth

**Comment by Cedd017** [comment] 2024-12-14 14:31
Is this working now?

**Comment by cmalf** [comment] 2024-12-16 03:32
@ at Everyone!
- The problem has been resolved
- Closing this issue.!

**Closed by cmalf** 2024-12-16 03:32 UTC
Labels: bug

**Comment by aliaksei777** [comment] 2024-12-16 07:49
Hi @cmalf, could you share, please, how it was resolved? As I can see there're no new updates in repository. 🌝

**Comment by Solana0x** [comment] 2024-12-16 12:01
@cmalf could you tell me what was the fixes that fixed the code? thanks

**Comment by Solana0x** [comment] 2024-12-16 14:48
Hi could you tell what changes you made? i need to update my github repo too??
